# Generated by Django 4.1.2 on 2022-10-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_remove_blogg_url_blogg_date'),
        ('blogg', '0002_rename_descriptionb_blogg_description_and_more'),
    ]

    operations = [
    ]
